### PR TITLE
Hello world 🖖

### PR DESCRIPTION
**Pull request by yajo**
Let's start this thing. :blush:

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't it be ansible-role-doodba?

**Comment by yajo** [comment]
Nope, that's one of the best things: this is fully decoupled :yum:. You can run doodba or other docker services. Role for managing doodba can come later in the stack :wink:

**Comment by pedrobaeza** [comment]
OK, great. This will support official Odoo docker image?

**Comment by yajo** [comment]
This will support anything that runs in Docker :yum: :whale: 

It's not related to Odoo at all.

**Comment by pedrobaeza** [comment]
Uhm, OK, I'm not getting the sense of this, but if you say so. Do you know https://github.com/OCA/ansible-odoo?

**Comment by yajo** [comment]
I know it, and it's not for the Doodba world.

**Pull request merged**
